server:
  port: 443   # https端口
  ssl:
    key-store: 3702162_wechat.coding-jiangzh.com.pfx  # tomcat ssl证书
    key-store-password: 49Jk65Pi  # 证书密码

template:
  templates:
    - {"templateId":"1","templateFilePath":"./template/template.json","active": true}
    - {"templateId":"2","templateFilePath":"./template/template.json","active": false}
  template-result-type: 0  # 0-文件获取 1-数据库获取 2-ES
  template-result-file-path: "./template/templateResult.json"

wechat:
  kafka:
    bootstrap_servers: "127.0.0.1:9092"
    acks_config: "all"
    partitioner_class: "tk.deriwtoua.kafka.producer.SamplePartition"


logging:
  config: classpath:logback.xml