server:
  port: 9091
# 使用数据模拟 不开启数据库查询
#spring:
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/springcloud
#    username: root
#    password: root
#mybatis:
#  type-aliases-package: tk.deriwotua.user.pojo
spring:
  application:
    #应用名
    name: user-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
      # EurekaServer地址,多个地址以','隔开
      #defaultZone: http://127.0.0.1:10086/eureka,http://127.0.0.1:10087/eureka
  instance:
    lease-expiration-duration-in-seconds: 90
    lease-renewal-interval-in-seconds: 30